# Generated by Django 4.1.7 on 2023-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('art', 'Статья'), ('new', 'Новость')], default='art', max_length=3),
        ),
    ]
