# Generated by Django 4.1.7 on 2023-03-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
    ]
